---
baseline_timezone: "UTC"

baseline_packages:
  - ufw
  - fail2ban
  - unattended-upgrades
  - auditd
  - audispd-plugins
  - apt-listchanges
  - needrestart
  - libpam-pwquality
  - curl
  - gnupg
  - lsb-release
  - apt-transport-https
